InMobi Advanced Bidding Adapters
mopub/mopub-android-mediation pull request #311
Opened 2020-12-07 15:12 UTC by RajSuvariya-InMobi

2021-01-08 19:31 UTC, rjmtweep commented on InMobi/src/main/java/com/mopub/utils/Utils.kt
> +}
missing newline

2021-01-08 19:31 UTC, rjmtweep commented on InMobi/src/main/java/com/mopub/mobileads/InMobiSDKAdapterConfiguration.kt
> +}
missing newline

2021-01-08 19:59 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiSDKAdapterConfiguration.kt
> +import com.example.inmobi.BuildConfig
The `com.example.inmobi.BuildConfig` returns error

2021-01-08 19:59 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +class InMobiBannerAd : BaseAd() {
Would we need `open` keyword here as well?

2021-01-11 06:01 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +        } catch (sdkNotInitExe: SdkNotInitializedException) {
When any InMobi ad object is created without SDK init, the construction of that object itself will throw SDK not initialized exception.

2021-01-11 06:05 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +class InMobiBannerAd : BaseAd() {
I do not see any use case when InMobiBannerAd class would be extended by any other class. Do you see any use case for the same?

2021-01-11 06:20 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +    private var mInMobiBannerContainer: FrameLayout? = null
Yes, this is required as of now for supporting MoPub InMobi integration due to some internal behavior of InMobi Banner. We are working to change this internal behavior but it is expected to take time. Once we change the internal behavior we will remove this intermediate container.

2021-01-13 13:20 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +class InMobiBannerAd : BaseAd() {
Not on our end. Wanted to see if you'd need a case for the container view. 
👍🏼

2021-01-13 13:47 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiSDKAdapterConfiguration.kt
> +            val accountId = if (configuration.containsKey(ACCOUNT_ID)) configuration[ACCOUNT_ID] else null
Are there any special checks needed for accountId parameter like the one we're discussing over in iOS:
Please see here: https://github.com/mopub/mopub-ios-mediation/pull/354/files#r556529703

2021-01-13 14:46 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiGDPR.kt
> +        var gdprConsentDictionary: JSONObject? = null
Could you please provide example code on how to populate the GDPR consent?

2021-01-14 16:13 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +                display.getMetrics(dm)
These methods are deprecated. Can you please suggest an alternative use?
![image](https://user-images.githubusercontent.com/47573140/104617458-5c0d1d80-5683-11eb-94bc-88d6c44a3d18.png)

2021-01-18 06:06 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +        if (mAdWidth <= 0 || mAdHeight <= 0) {
Yes, anything greater than width>0 && height>0 is valid

2021-01-18 06:32 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/utils/Utils.kt
> +            InMobiAdRequestStatus.StatusCode.NETWORK_UNREACHABLE -> MoPubErrorCode.NETWORK_INVALID_STATE
No, it means the internet is not available on the user's device. For other server issues InMobi SDK will return InMobiAdRequestStatus.StatusCode.SERVER_ERROR or InMobiAdRequestStatus.StatusCode.REQUEST_TIMED_OUT

2021-01-18 06:46 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/utils/Utils.kt
> +            InMobiAdRequestStatus.StatusCode.REQUEST_INVALID -> MoPubErrorCode.ADAPTER_CONFIGURATION_ERROR
InMobiAdRequestStatus.StatusCode.REQUEST_INVALID means the publisher has passed some values which are causing ad network request to fail either on client-side checks before making ad request or at the ad server end.

2021-01-18 07:58 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiSDKAdapterConfiguration.kt
> +            val accountId = if (configuration.containsKey(ACCOUNT_ID)) configuration[ACCOUNT_ID] else null
For Android, we have this validation internally and if the required length is invalid then it results in init failure so need to have checked at the adapter level

2021-01-18 08:00 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiGDPR.kt
> +        var gdprConsentDictionary: JSONObject? = null
You can check the table under this link https://support.inmobi.com/monetize/android-guidelines#page__initializing-the-sdk
It explains keys and possible values for each key.

2021-01-18 08:57 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +                display.getMetrics(dm)
Updated

2021-01-18 08:57 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/utils/Utils.kt
> +            InMobiAdRequestStatus.StatusCode.REQUEST_INVALID -> MoPubErrorCode.ADAPTER_CONFIGURATION_ERROR
I have updated the mapping please check

2021-01-19 14:17 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiSDKAdapterConfiguration.kt
> +            val accountId = if (configuration.containsKey(ACCOUNT_ID)) configuration[ACCOUNT_ID] else null
Got it. This is a very common mistake that publishers do. We'd like to be very informative on this one. If there's not many checks, can we implement them here on the adapter level?
If not, would InMobi SDK print this in detail, such that account id is not in good format?

2021-01-21 14:30 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiInterstitialAd.kt
> +                                    if (iterator.hasNext()) {
The flow here is unclear to us. Could you please explain what will come on the rewards map? Is it always only one single item with the ad's set reward? 
Such that: `{"rewardKey":"rewardValue}` and that's it - with no other elements?

2021-01-21 14:30 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +                setExtras(Utils.extras)
Are these only needed for banner? Or do we need this for interstitial and RV's as well?

2021-01-21 15:31 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +                    override fun onAdDisplayed(inMobiBanner: InMobiBanner) {
@hmertkahraman 
onAdDisplayed - Fired when anything fullscreen is opened in the app (expanded, in-app browser etc.) when the user clicks on the banner ad.

2021-01-21 15:32 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiInterstitialAd.kt
> +                        override fun onAdDisplayed(ad: InMobiInterstitial, info: AdMetaInfo) {
@hmertkahraman 
onAdDisplayed - Fired when anything fullscreen is opened in the app (fullscreen activity, in-app browser etc.)

2021-01-21 15:32 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +                setExtras(Utils.extras)
No extras are needed for all formats

2021-01-21 15:33 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +                setExtras(Utils.extras)
It was a miss from our end for Int / RV, will do the changes

2021-01-21 15:40 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiInterstitialAd.kt
> +                                    if (iterator.hasNext()) {
Publishers can set multiple reward key-pair values and which are provided to them via this callback as a map. But as MoPub only allows one we are passing the last value from the Map to MoPub

2021-01-22 09:11 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiBannerAd.kt
> +                setExtras(Utils.extras)
Changes are pushed.

2021-01-25 20:33 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiInterstitialAd.kt
> +                        override fun onAdDisplayed(ad: InMobiInterstitial, info: AdMetaInfo) {
Hi @RajSuvariya-InMobi,

Can we ask which one of the mentioned above cases would you fit this description, A or B ?

2021-01-25 20:38 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiInterstitialAd.kt
> +                                    if (iterator.hasNext()) {
Thanks. Here, if I'm not wrong, the iterator seems to traverse only once by hasNext(). So this would ideally get the first element on the map..? Would this matter as you mention `last value`?

2021-01-27 11:11 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiInterstitialAd.kt
> +                                    if (iterator.hasNext()) {
Yeah sorry, the adapter will provide the first key-pair value to MoPub

2021-01-27 11:12 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiInterstitialAd.kt
> +                        override fun onAdDisplayed(ad: InMobiInterstitial, info: AdMetaInfo) {
That would be A.

2021-02-04 15:14 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiAdapterConfiguration.kt
> +        const val ACCOUNT_ID_KEY = "accountid"
@hmertkahraman I saw that the current setup from MoPub is using this key where every character is a small case. If this key is going to be written by the publisher on the MoPub UI then I would recommend it to be changed to camelCase.

Also same goes for placementId as well

2021-02-04 15:16 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiAdapterConfiguration.kt
> +                val mopubSdkClassRef = Class.forName(MoPub::class.java.name)
I have again changed this to use reflection. As the MoPubSDK.SDK_VERSION is a static field. So compiler will do a static binding while generating adapter aar / jar files. So it would end up hardcoding the "tp-ver" value as the MoPub SDK's version with which the source was compiled. Where as we need the version with which it is integrated at runtime.

2021-02-04 15:19 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiAdapterConfiguration.kt
> +                val consentObject = InMobiGDPR.gdprConsentDictionary ?: run {
@hmertkahraman 
This has been changed to consider a scenario when Publisher wants to provide IAB string to InMobi. If they don't set this value then we will use the consent converted from MoPub's consent

2021-02-08 22:11 UTC, hmertkahraman requested changes

2021-02-08 22:11 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiAdapterConfiguration.kt
> +                    consentObject.put(InMobiSdk.IM_GDPR_CONSENT_IAB, null)
Please note that we are passing `NULL` for IAB String. Would you confirm this is OK?

2021-02-08 22:11 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiRewarded.kt
> +            MoPubLog.log(adNetworkId, AdapterLogEvent.SHOW_FAILED, ADAPTER_NAME,
Can we use  onInMobiAdFailWithEvent method like [here](https://github.com/mopub/mopub-android-mediation/pull/311/files#diff-426e8205c0d2b08e99744ae82141b133a7349d2ae876651fc1d82c2651654a33R114-R117).

2021-02-08 22:11 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiInterstitial.kt
> +            MoPubLog.log(adNetworkId, AdapterLogEvent.SHOW_FAILED, ADAPTER_NAME,
Can we use  onInMobiAdFailWithEvent method like [here](https://github.com/mopub/mopub-android-mediation/pull/311/files#diff-426e8205c0d2b08e99744ae82141b133a7349d2ae876651fc1d82c2651654a33R114-R117).

2021-02-08 22:11 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiInterstitial.kt
> +            MoPubLog.log(AdapterLogEvent.CUSTOM, ADAPTER_NAME, "InMobi interstitial is still loading." +
Can we add to the message: "InMobi interstitial is not ready yet. It is still loading. Please make sure ad is loaded."

2021-02-08 22:11 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiRewarded.kt
> +            MoPubLog.log(AdapterLogEvent.CUSTOM, ADAPTER_NAME, "InMobi rewarded video ad is still loading." +
Can we add to the message: "InMobi interstitial is not ready yet. It is still loading. Please make sure ad is loaded."

2021-02-08 22:11 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiGDPR.kt
> +package com.mopub.mobileads
Hi @RajSuvariya-InMobi ,
Going forward we are not using any separate files apart from Adapter Config classes. Would you please be able to remove this class and add it's functionality back in Config class?

2021-02-08 22:12 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiAdapterConfiguration.kt
> +                val consentObject = InMobiGDPR.gdprConsentDictionary ?: run {
Is this the reason why you wanted to move InMobiGDPR out of this class' scope?
Regardless, would you please be able to explain us the full expected flow?

2021-02-08 22:14 UTC, hmertkahraman commented
Hi @RajSuvariya-InMobi ,
I've gone through your updates and responded to the open items. If you can make necessary changes, I will make one other round of testing on our end with the latest updates.

2021-02-08 22:22 UTC, hmertkahraman commented
@RajSuvariya-InMobi , would you also be able to rename the Rewarded Video Adapter to:
`InMobiRewardedVideo` - this is a recent decision we made.
Thanks.

2021-02-09 12:04 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiAdapterConfiguration.kt
> +        const val ACCOUNT_ID_KEY = "accountid"
Sure will do it, wanted to let you know as this would require backend changes on MoPub side

2021-02-09 12:08 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiAdapterConfiguration.kt
> +                val consentObject = InMobiGDPR.gdprConsentDictionary ?: run {
@hmertkahraman This would be shared by the InMobi product team if not already done

2021-02-09 12:21 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiAdapterConfiguration.kt
> +        initialiseInMobi(configuration, context, object : InitCompletionListener {
@hmertkahraman Noted!

But want to understand this exactly, MoPub is expecting an async callback via listener then what is the harm in depending on InMobi's callback. We have been using this in custom adapters and we haven't faced any issues so far. Also, InMobi init provides a callback within milliseconds. So is it fine if we depend on this?

2021-02-09 12:26 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiAdapterConfiguration.kt
> +                    consentObject.put(InMobiSdk.IM_GDPR_CONSENT_IAB, null)
This should be rectified once the GDPR flow is confirmed.

2021-02-09 12:28 UTC, RajSuvariya-InMobi commented on InMobi/src/main/java/com/mopub/mobileads/InMobiRewarded.kt
> +            MoPubLog.log(adNetworkId, AdapterLogEvent.SHOW_FAILED, ADAPTER_NAME,
It's not a show failure it's because InMobi is still loading the ad. This should not happen if the Publisher is calling show after adLoadSuccess callback

2021-02-09 18:01 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiRewarded.kt
> +            MoPubLog.log(adNetworkId, AdapterLogEvent.SHOW_FAILED, ADAPTER_NAME,
Hi Raj,
We treat these as show failed errors. [This](https://github.com/mopub/mopub-android-mediation/pull/311/files#diff-426e8205c0d2b08e99744ae82141b133a7349d2ae876651fc1d82c2651654a33R109-R114) method we mentioned accepts interaction listener etc. so that also handles interaction related events. Would you please update RV and Interstitial adapters using this? Thanks

2021-02-09 19:22 UTC, hmertkahraman commented on InMobi/src/main/java/com/mopub/mobileads/InMobiAdapterConfiguration.kt
> +        initialiseInMobi(configuration, context, object : InitCompletionListener {
Hi Raj,
Currently our requirement is not to wait, and this is being standardized across our all networks adapters. We are working an infrastructure update which would enhance the initialization sequence soon on our end. After that we will be able to move to this fashion. Until that happens later this year, unfortunately at this time we need to go ahead with the way described above. Would appreciate if you can revise it back to latest submission instead, [here](https://github.com/mopub/mopub-android-mediation/pull/311/commits/3e2f9cd8830318805e38436a60cfc16d003c9a1c#diff-a0c6b259b20c830d6a2df464633a858a87d21924f030dc8831a3affe016221ceL53-L57). Thanks!

2021-04-28 15:44 UTC, hmertkahraman commented
Released internally [here](https://github.com/mopub/mopub-android-mediation/commit/3e2e5e973c7d00fd646eede0f641848e8be97927)

2021-04-28 15:44 UTC, closed without merging