Ogury - 5.0.9.0
mopub/mopub-android-mediation pull request #346
Opened 2021-04-29 13:40 UTC by cvlaminck

# Description

Add support for Interstitial, Rewarded video and Banner from Ogury.
Transmit MoPub's consent to Ogury.

2021-04-30 17:12 UTC, chauduyphanvu requested changes
First pass done

2021-04-30 17:12 UTC, chauduyphanvu commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +    }
Banners are shown immediately upon load, so we don't need to override `show()`. 

`mListenerHelper.setInteractionListener(mInteractionListener);` can probably be called when the ad is loaded.

2021-04-30 17:12 UTC, chauduyphanvu commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +        int adHeight = (iAdHeight != null) ? iAdHeight : 0;
`final`

2021-04-30 17:12 UTC, chauduyphanvu commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +            return false;
I'd add a log message explaining what's happening and what publishers can do to overcome it.

2021-04-30 17:12 UTC, chauduyphanvu commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +        if ((mopubHeight < oguryBannerAdSize.getHeight()) || (mopubWidth < oguryBannerAdSize.getWidth())) {
Seems like there are double parentheses.

2021-04-30 17:12 UTC, chauduyphanvu commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +        OguryBannerAdSize adSize = getBannerAdSize(adData.getAdWidth(), adData.getAdHeight());
`final`

2021-04-30 17:12 UTC, chauduyphanvu commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +    }
No need to do this for banner ads

2021-05-03 09:12 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryAdapterConfiguration.java
> +        }
The asset key is already checked in the startOgurySdk methods. I did not add the check to avoid code duplication.

2021-05-03 09:12 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +        return mAdUnitId;
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:12 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +                        MoPubErrorCode.NETWORK_NO_FILL.getIntCode(), MoPubErrorCode.NETWORK_NO_FILL);
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:12 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryRewardedVideo.java
> +        return mAdUnitId;
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:12 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryRewardedVideo.java
> +        OguryInitializer.updateConsent();
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:12 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryRewardedVideo.java
> +                        MoPubErrorCode.NETWORK_NO_FILL.getIntCode(), MoPubErrorCode.NETWORK_NO_FILL);
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:12 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryRewardedVideo.java
> +    private OguryOptinVideoAd mOptinVideo;
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:12 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryConfigurationParser.java
> +public class OguryConfigurationParser {
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:12 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryInitializer.java
> +public class OguryInitializer {
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:13 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryInterstitial.java
> +        OguryInitializer.updateConsent();
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:13 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryInterstitial.java
> +                        MoPubErrorCode.NETWORK_NO_FILL.getIntCode(), MoPubErrorCode.NETWORK_NO_FILL);
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:13 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryAdListenerHelper.java
> +        MoPubErrorCode errorCode = getMoPubErrorCodeForError(error);
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:14 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryRewardedVideo.java
> +            }
I prefer to call the interaction listener directly to avoid having forging an OguryError for the listener helper.

2021-05-03 09:14 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryInterstitial.java
> +            }
I prefer to call the interaction listener directly to avoid having forging an OguryError for the listener helper.

2021-05-03 09:14 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryInterstitial.java
> +        return mAdUnitId;
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:14 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryInitializer.java
> +        PersonalInfoManager personalInfoManager = MoPub.getPersonalInformationManager();
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:14 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryInitializer.java
> +            Boolean gdprApplies = personalInfoManager.gdprApplies();
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:14 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryInitializer.java
> +
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:15 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryInitializer.java
> +        String assetKey = OguryConfigurationParser.getAssetKey(adDataExtras);
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:15 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryInitializer.java
> +        OguryConfiguration oguryConfiguration = new OguryConfiguration.Builder(context, assetKey)
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:15 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryInitializer.java
> +            MoPubLog.log(CUSTOM, ADAPTER_NAME, "Ogury's initialization not started as the asset key is missing or empty.");
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:15 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +    }
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:15 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +        int adHeight = (iAdHeight != null) ? iAdHeight : 0;
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:15 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +            return false;
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:15 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +        if ((mopubHeight < oguryBannerAdSize.getHeight()) || (mopubWidth < oguryBannerAdSize.getWidth())) {
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:15 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +        OguryBannerAdSize adSize = getBannerAdSize(adData.getAdWidth(), adData.getAdHeight());
Fixed in 4469f0f6c7b1397383cd7718bde7c7bda7c20630.

2021-05-03 09:16 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +    }
I moved the initialization code into it as for interstitial and rewarded video.

2021-05-03 09:16 UTC, cvlaminck commented on Ogury/src/main/java/com/mopub/mobileads/OguryBanner.java
> +        OguryBannerAdSize adSize = getBannerAdSize(adData.getAdWidth(), adData.getAdHeight());
Fixed in e786df2f2b90b7a11de29d4320bacf6e369dcded.

2021-06-03 20:38 UTC, chauduyphanvu commented
Done in https://github.com/mopub/mopub-android-mediation/commit/65b203cd606746be38f2456cd260d7874bf7ca23. Thanks!

2021-06-03 20:38 UTC, closed without merging