[InMobi] Support for native ad format
mopub/mopub-android-mediation pull request #365
Opened 2021-07-06 09:11 UTC by RajSuvariya-InMobi

2021-09-09 15:18 UTC, p158276 requested changes

2021-09-09 15:18 UTC, p158276 commented on InMobi/src/main/java/com/mopub/nativeads/InMobiNative.kt
> +            override fun onAdClicked(inMobiNative: InMobiNative) {
If the user clicks the same ad multiple times, Is InMobi server end only count 1 time? 
If not we shouldn't do the dedupe logic in the adapter.

2021-09-09 15:18 UTC, p158276 commented on InMobi/src/main/java/com/mopub/nativeads/InMobiNative.kt
> +                MoPubLog.log(AdapterLogEvent.CUSTOM, TAG, "InMobi Native ad onAdStatusChanged")
What kind of status change? Are there any detail information that we can address in the log?

2021-09-09 15:18 UTC, p158276 commented on InMobi/src/main/java/com/mopub/nativeads/InMobiNative.kt
> +    private var inMobiStaticNativeAd: InMobiNativeAd? = null
As you'll set the videoListener [here](https://github.com/mopub/mopub-android-mediation/pull/365/files#diff-806afec5efca112cb5dbe80d2e2aa57e3406669c05da518824a81cf576ca8628R252). To avoid confusion, should we name the variable other than static?

2021-09-09 15:29 UTC, p158276 commented
Hi @RajSuvariya-InMobi ,
Before changing the code, can you merge fetch some log change I put in this repository? (https://github.com/mopub/mopub-android-mediation/tree/inmobi-native-ad)
Thanks.

2021-09-15 05:33 UTC, harshit-inmobi commented on InMobi/src/main/java/com/mopub/nativeads/InMobiNative.kt
> +    private var inMobiStaticNativeAd: InMobiNativeAd? = null
renamed variable to `inMobiNativeAd`

2021-09-15 05:33 UTC, harshit-inmobi commented on InMobi/src/main/java/com/mopub/nativeads/InMobiNative.kt
> +                MoPubLog.log(AdapterLogEvent.CUSTOM, TAG, "InMobi Native ad onAdStatusChanged")
Removed this callback method as it is not functional

2021-09-15 05:35 UTC, harshit-inmobi commented on InMobi/src/main/java/com/mopub/nativeads/InMobiNative.kt
> +            override fun onAdClicked(inMobiNative: InMobiNative) {
InMobi server does the dedupe for click. we can keep this check in adapter code.

2021-09-15 05:38 UTC, harshit-inmobi commented on InMobi/src/main/java/com/mopub/nativeads/InMobiNative.kt
> +                    InMobiAdRequestStatus.StatusCode.INTERNAL_ERROR -> {
These mappings are specific native ads and are not used anywhere else, so we can keep it this way.

2021-10-04 13:31 UTC, harshit-inmobi commented on InMobi/src/main/java/com/mopub/nativeads/InMobiNative.kt
> +            override fun onAdClicked(inMobiNative: InMobiNative) {
@p158276 If I removed the dedupe logic from adapter, will Mopub server count it as multiple clicks and might cause sync issue with InMobi server for number of clicks?

2021-10-04 13:54 UTC, p158276 commented on InMobi/src/main/java/com/mopub/nativeads/InMobiNative.kt
> +            override fun onAdClicked(inMobiNative: InMobiNative) {
Hi, we'll only send one time to our server. So you don't need to do the dedupe logic in our adapter.

2021-10-07 12:17 UTC, harshit-inmobi commented on InMobi/src/main/java/com/mopub/nativeads/InMobiNative.kt
> +            override fun onAdClicked(inMobiNative: InMobiNative) {
@p158276  this is fixed, please check

2022-01-14 09:01 UTC, closed without merging