New Adapter - Supporting Banner Ads In ironSource SDK
mopub/mopub-android-mediation pull request #389
Opened 2021-08-24 17:34 UTC by itaias

This is a pull request that contains a new adapter for Banner Ads of ironSource SDK, under MoPub platform.
The Banner adapter developed in this pull request meant to support only bidding mode, which means it will always expect an ADM.
The adapter was tested with / without other Ad types (as a custom adapter), following the same guidelines and feedback we received from MoPub team.

2021-08-24 19:49 UTC, chauduyphanvu requested changes
Left some comments. Code review looks good overall pending any end-to-end testing results. 

Also, could you put back the files you deleted in `Testing/`?

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceAdapterConfiguration.java
> +        boolean canCollectPersonalInfo = MoPub.canCollectPersonalInformation();
`final`

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceAdapterConfiguration.java
> +        boolean canCollectPersonalInfo = MoPub.canCollectPersonalInformation();
Also, does this require ironSource to have been initialized first or will it work at this point?

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceAdapterConfiguration.java
> +    public static MoPubErrorCode convertISNBannerErrorToMoPubError (IronSourceError ironSourceError) {
```suggestion
    public static MoPubErrorCode convertISNBannerErrorToMoPubError(IronSourceError ironSourceError) {
```

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceAdapterConfiguration.java
> +                moPubErrorCode = MoPubErrorCode.NETWORK_INVALID_STATE;
You can also return your `MoPubErrorCode` directly in each of the `case`s as well. No need for assignments.

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +    // region private vars
Remove?

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +    // endregion
Probably not needed

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +    // region Base Ad Override
Not needed

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +        MoPubLog.log(CUSTOM, ADAPTER_NAME, "IronSource IronSourceBanner() hash= " + this.hashCode());
This is probably not needed. I don't see a use case for logging the hashcode.

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +        IronSource.setConsent(canCollectPersonalInfo);
It looks like this has already been done in the AdapterConfiguration. Is it also needed here? How often do you wish to receive the GDPR consent signal?

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +            String applicationKey = extras.get(APPLICATION_KEY);
`final`

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +        MoPubLog.log(CUSTOM, ADAPTER_NAME, "IronSource load() hash= " + this.hashCode());
Probably not needed.

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +                    MoPubErrorCode.ADAPTER_CONFIGURATION_ERROR);
We can make these 1 (or 2 at max) lines.

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +                    MoPubErrorCode.ADAPTER_CONFIGURATION_ERROR);
I'd also add a custom log message explaining the reason why we are failing.

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +            );
1 line

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +        String adUnitFormat = extras.get(ADUNIT_FORMAT);
`final`

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +            MoPubLog.log(CUSTOM, ADAPTER_NAME, "ADM field is missing populated. Will not load.");
```suggestion
            MoPubLog.log(CUSTOM, ADAPTER_NAME, "Advanced Bidding ad markup not available. Aborting the ad request.");
```

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +        MoPubLog.log(CUSTOM, ADAPTER_NAME, "IronSource getAdView()");
Not needed

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +        String heightValue = extras.get(AD_HEIGHT);
`final`

2021-08-24 19:49 UTC, chauduyphanvu commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +        String widthValue = extras.get(AD_WIDTH);
`final`

2021-08-25 09:53 UTC, itaias commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceAdapterConfiguration.java
> +        boolean canCollectPersonalInfo = MoPub.canCollectPersonalInformation();
Setting consent can be done without SDK initialization, so it will work at this point

2021-08-25 10:02 UTC, itaias commented on IronSource/src/main/java/com/mopub/mobileads/IronSourceBanner.java
> +        IronSource.setConsent(canCollectPersonalInfo);
it's a bit hard to say how often publishers change this, but since we are actually care about this value when loading ads, it seems like a good thing to observe it everytime the class loaded. WDYT?

2021-09-07 13:17 UTC, chauduyphanvu approved these changes

2021-09-07 13:18 UTC, chauduyphanvu commented
Done in https://github.com/mopub/mopub-android-mediation/commit/cb7fe38aa59ae8180f788cd0e1177051e64410ce. Thanks for the PR!

2021-09-07 13:18 UTC, closed without merging